### ISSUE TITLE
「Domino」→「ユーザー Bean」ページでの未翻訳

### ISSUE THREAD

**Issue by hkomine** [OpenNTF/JapaneseExtLibrarySamples#16]
「Canonical Name」、「Abbreviated Name」 の翻訳が不適切。
現状：
「Canonical Name」 → 「名前[Canonical]形式」
「Abbreviated Name」  → 「名前[Abbreviate]形式」

また「Viewer」の訳も気になる。

**Comment by chemp7** [comment]
デザイナーヘルプを参考に以下に変更しました。

「Canonical Name」
"名前 ［階層付き］ （id）"
"名前 ［階層付き］ （canonicalName）"

「Abbreviated Name」 
"名前 ［省略］ （abbreviatedName）"

「Viewer」は良いのが思いつかなかったのでそのままです・・・

**Comment by hkomine** [comment]
修正を確認したのでクローズします。
「Viewer」はいまのまま「参照者」にしておきましょう。問題があると思った人が Issue をあげるということで。
