### ISSUE TITLE
「iNotes」→「バーチャルリスト 2」ページでの「ソート」タブのビューの列名が未翻訳

### ISSUE THREAD

**Issue by chemp7** [OpenNTF/JapaneseExtLibrarySamples#30]
iNotes List View コントロールでビューの列名を直接取得している為、翻訳する場合は方法を要検討。

**Comment by hkomine** [comment]
同じ NSF の「AllContacts」ビューの列名をそのまま表示しているようです。ビューの設計を変更する必要がありますが、これは XPages や Extension Library の国際化で対応できるものではないと思います。

No Plan to Fix で、この Issue はクローズしたいですが・・・。

**Comment by acchan** [comment]
翻訳不可能なところなのでクローズ
