### ISSUE TITLE
20130205 ここにチェックを入れないとサンプルデータ作成はエラーに

### ISSUE THREAD

**Issue by hkomine** [OpenNTF/JapaneseExtLibrarySamples#36]
XPagesEXT_J.nsf での問題です。

![20130205 png](https://f.cloud.github.com/assets/2735756/134226/67c795f6-70c7-11e2-8f57-4ad8c35122d1.png)

**Comment by hkomine** [comment]
OpenNTF.org からダウンロードした XPagesJDBC_J.nsf では、あらかじめチェックされていました。
GitHub から取り出してビルドしたファイルでの問題でしょうか？

**Comment by hkomine** [comment]
XPages_JDBC_J.nsf ではチェックされていましたが、XPagesEXT_J.nsf ではチェックがついていなかった。

**Comment by onoat** [comment]
元の英語版の XPagesExt.nsf でも com.ibm.xsp.extlibx.library にはチェックがついていないみたいです。
私の環境ではチェックがついていなくてもサンプルデータ作成はちゃんと動いたのですが、他の方の環境では再現しますでしょうか？

**Comment by hkomine** [comment]
あらためて 853.20121217-1354_Ja-Beta2 の中の XPagesExt_J.nsf を Domino サーバーにおいて署名してブラウザから開きました。com.ibm.xsp.extlibx.library にはチェックが付いていませんでしたが、1セットのサンプルデータ（小さいサンプル）の作成は問題なく動作しました。

テスト環境： Domino 8.5.3 FP1 + 日本語の言語パック
