### ISSUE TITLE
20130205 リンク先文書が表示されず

### ISSUE THREAD

**Issue by hkomine** [OpenNTF/JapaneseExtLibrarySamples#40]
![20130205 ](https://f.cloud.github.com/assets/2735756/134231/9ed653de-70c7-11e2-9947-220661c1ddad.png)

**Comment by hkomine** [comment]
元の XPagesEXT.nsf でも同じ問題が再現する。

**Comment by acchan** [comment]
コアにレポートしてクローズする

**Comment by hkomine** [comment]
コアにレポートしました。
http://www.openntf.org/internal/home.nsf/defect.xsp?action=openDocument&documentId=BEAC868F4883534686257B1D000D3A4A
