### ISSUE TITLE
20130205 初期データ作成前の表示のずれ

### ISSUE THREAD

**Issue by hkomine** [OpenNTF/JapaneseExtLibrarySamples#41]
![20130205 ](https://f.cloud.github.com/assets/2735756/134232/adb933ee-70c7-11e2-9a74-4c8d834e02c2.png)

**Comment by acchan** [comment]
英語版での再現確認および IE の互換モードでの再現を確認後にアクションを考える

**Comment by GuyLocke** [comment]
右上の[管理]ボタンや、その上の[キーワードを入力する]というテキストボックスのことですよね？
Win7 + IE9で確認したところ、
互換表示ONでは、画像と同じようにずれて表示されましたが、
互換表示をOFFにしたところ、ずれずに正しい位置に表示されました。
オリジナルのXPagesEXT.nsf（英語版）でも同様の結果となったので、ブラウザ側の問題かと思います。

また、Win8 + IE10でも、上記と同様の結果になりました。
互換表示の設定は「ON」がデフォルトのようですので、注意が必要かもしれません。（一応、インストール時には聞かれるのですが、スルーする可能性が大きいです）

**Comment by masahikosatoh** [comment]
NAX環境（Windows7+IE9）では、御代さんの記載通り、
・互換表示ON：画面表示が崩れる
・互換表示OFF：画像表示が崩れない
となりました。やはり、IE側の問題ですね。このDBを利用する場合には「互換表示はOFF」とするほうが
良さそうですね。

**Comment by chemp7** [comment]
結果は同じですが、気になったので私も確認してみました。

・Win XP + IE7 ：画面表示が崩れる。
・Win XP + IE8 ：OK
・Win XP + IE8　（互換表示） ：画面表示が崩れる。
・Win 7 + IE9 ：OK
・Win 7 + IE9　（互換表示） ：画面表示が崩れる。
・Win 7 + IE10 ：OK
・Win 7 + IE10　（互換表示） ：画面表示が崩れる。
・Google Chrome 25.0.1364.97 m：OK
・Firefox 19.0：OK

IE7 の CSS の対応度の問題でしょうか。。。

**Comment by acchan** [comment]
互換表示で表示が崩れる件はまとめてコアにレポートする
