### ISSUE TITLE
20130205 微妙なずれ＆IE9ではシンプルテキストエリアが機能しないけどたぶんDojo自身の問題

### ISSUE THREAD

**Issue by hkomine** [OpenNTF/JapaneseExtLibrarySamples#42]
![20130205 IE9 Dojo ](https://f.cloud.github.com/assets/2735756/134234/c4605aaa-70c7-11e2-82df-3ff1a1b61b78.png)

**Comment by acchan** [comment]
英語版および互換モードでの問題の再現を確認する

**Comment by masahikosatoh** [comment]
一つ目：微妙なずれに関しては、互換モードをOFFにすることで解決。英語版でも同じでした。
二つ目：シンプルテキストエリアは、英語版でも互換モードでもサイズ変更は不可でした。
　　　　こちらは、Dojo側の問題かもしれないです。

**Comment by acchan** [comment]
1 つ目に関しては互換モードの問題なので、まとめてコアにレポート

2 つ目に関しては以下のサンプルでも再現するため Dojo の問題。
ExtLib Japan としてはこれ以上は調査しない。
http://dojotoolkit.org/reference-guide/1.8/dijit/form/SimpleTextarea.html
