### ISSUE TITLE
XPagesEXT: 20130225拡張フォームコントロール×クリックできず。IEとFirefoxで発生Chromeは発生せず、なお、英語版も同じ

### ISSUE THREAD

**Issue by hkomine** [OpenNTF/JapaneseExtLibrarySamples#61]
![20130225 IE Firefox Chrome ](https://f.cloud.github.com/assets/2735756/194959/14c987d8-7fcc-11e2-8bfa-265001a24364.png)

**Comment by hkomine** [comment]
再現しないですぅ～。

**Comment by chemp7** [comment]
似た現象は、Windows 7 + IE9 の互換表示【オフ】時に発生しました。
互換表示【オン】時には☓ボタンは逃げませんでした。
ただ、今回ダンロードしたベータ版ではダイアログ表示前に別のエラーが表示されたのでもう少し環境を見直してみます。

あと、上記画像でダイアログのタイトルが英語のままなのが気になりました。「Select A Value」

蛇足
本当に逃げますね・・・伸びた後の☓を押そうとすると縮むし・・・

**Comment by hkomine** [comment]
IE9 + Win7 で Domino Designer 9.0 で再現しました。
コアのバグとしてレポートしました。

http://www.openntf.org/internal/home.nsf/xsp/.ibmmodres/persistence/DominoDoc-939-Details/02_1362033929512.png
