### ISSUE TITLE
XPagesEXT: 同じ英語に対する翻訳の不一致

### ISSUE THREAD

**Issue by hkomine** [OpenNTF/JapaneseExtLibrarySamples#73]
田村さんより
https://greenhouse.lotus.com/files/app#/file/feb60f4b-230a-4e5b-bba4-f4a8f84dc236

![ ](https://f.cloud.github.com/assets/2735756/280773/7951bbf8-9165-11e2-8ac2-55c156bde782.png)

**Comment by katoman** [comment]
#73 XPagesEXT: 同じ英語に対する翻訳の不一致
英文では値ピッカーも名前ピッカーも「Validated Text Boxes」ですが、日本語訳がそれぞれ異なっていますが、ご指摘のとおり「検査されたテキストボックス」が正解で、値ピッカーの「テキストボックスと妥当性監査機能の組み合わせ」は「検査されたテキストボックス」と修正すべきです。
