### ISSUE TITLE
XPagesJDBC: 同じ英語に対する翻訳の不一致（Select a XX）

### ISSUE THREAD

**Issue by yoyoyotamu** [OpenNTF/JapaneseExtLibrarySamples#76]
Select a Table の訳に不一致があります。
また、同様の英文ではSelect a State もありました。

![WS000000](https://f.cloud.github.com/assets/3519601/295408/be90a036-9489-11e2-8b81-97dfb8037797.JPG)
![WS000001](https://f.cloud.github.com/assets/3519601/295409/be92faac-9489-11e2-9348-063078ae707e.JPG)
![WS000002](https://f.cloud.github.com/assets/3519601/295410/beb233a4-9489-11e2-9dbc-dd07d83dcd5f.JPG)

**Comment by hkomine** [comment]
「テーブルを選択してください:」に統一しました。また「Select a State」については原文の違いを尊重し、そのままにしています。
