### ISSUE TITLE
翻訳の仕方について

### ISSUE THREAD

**Issue by GuyLocke** [OpenNTF/JapaneseExtLibrarySamples#79]
XPagesデモアプリの「イベント」タブにある関数の翻訳を行っているのですが、
一部の関数に「[ja| Select any of the following link to compute the field below: ]」という英文があります。
英文をそのまま翻訳すると、
「下にあるフィールドを計算したければ、次のリンクのどれかを選択してください」
みたいな感じだと思うのですが、
デモアプリの画面を見ても、その下にその関数の概要を端的にあらわす単語が表示されているだけで、リンクになっていません。
どうしたものでしょうか？そのまま翻訳して、画面の動きは無視してよいでしょうか？

例）@Author関数、@AttachmentNames関数等

**Comment by hkomine** [comment]
Facebook との重複コメントになりますが、サンプルデータが無いのが原因ではないでしょうか？
元のサンプルから文書をコピーすると表示されるようです。

**Comment by GuyLocke** [comment]
Facebook上で結論を出しましたので（後でデータを足せば正しい状態になるので、このまま翻訳を行う）、クローズします。
