### ISSUE TITLE
XPages: [フォーム]-[プロパティ]-[タブオーダー]のセクション内のボタンにロジックが無い。

### ISSUE THREAD

**Issue by chemp7** [OpenNTF/JapaneseExtLibrarySamples#80]
[フォーム]-[プロパティ]-[タブオーダー]のセクション内のボタンにロジックが無い。

よく似たページの[フォーム]-[プロパティ]-[アクセラレーターキー]のセクション内のボタンには、クリックすると文字を表示するロジックがある。

1) [フォーム]-[プロパティ]-[タブオーダー]
![git1](https://f.cloud.github.com/assets/2743233/553407/6a4c5702-c384-11e2-919b-0474ee3d0dbe.jpg)

2) [フォーム]-[プロパティ]-[アクセラレーターキー]
![git2](https://f.cloud.github.com/assets/2743233/553413/82710698-c384-11e2-93cc-bd55e45d64cd.jpg)

**Comment by chemp7** [comment]
タブオーダー、アクセラレーターキーの説明としては、ロジックがなくても問題ないのでクローズとしますか？

**Comment by hkomine** [comment]
前のバージョンでもないですね。ボタンのテストではないので、良いのではないでしょうか？
